<?php

return [
    [
        'user_id' => '1',
        'name' => 'Milo',
        'surname' => 'Marziali',
        'address' => 'Via Pompeo, 7',
        'services' => "Scienze dell'Alimentazione, Medicina estetica, Terapia del dolore",
        'photo' => 'avatar/11.png',
        'cv' => '',
        'telephone' => '3202486129',
    ],
    [
        'user_id' => '2',
        'name' => 'Cristian',
        'surname' => 'Pellegrini',
        'address' => 'Via Lodovico, 15',
        'services' => 'Ecocolordoppler dei vasi periferici, Ecocolordoppler dei tronchi sovra aortici, Elettrocardiogramma holter',
        'photo' => 'avatar/10.png',
        'cv' => '',
        'telephone' => '3985421605',
    ],
    [
        'user_id' => '3',
        'name' => 'Marco',
        'surname' => 'Zampieri',
        'address' => 'Via degli Oleandri, 11',
        'services' => 'Coronarografia, Trattamento cataratta, Visita oculistica',
        'photo' => 'avatar/9.png',
        'cv' => '',
        'telephone' => '3201542097',
    ],
    [
        'user_id' => '4',
        'name' => 'Vilma Maria',
        'surname' => 'Crivellaro',
        'address' => 'Via Baggio, 20',
        'services' => 'Radiografia ossea e delle articolazioni, Radiografia completa del tubo digerente, Radiografia completa del tubo digerente',
        'photo' => 'avatar/1.png',
        'cv' => '',
        'telephone' => '3501248961',
    ],
    [
        'user_id' => '5',
        'name' => 'Giorgio',
        'surname' => 'Francuzzi',
        'address' => 'Via Mar Nero, 30',
        'services' => 'Riabilitazione motoria, Riabilitazione respiratoria, Logopedia',
        'photo' => 'avatar/6.png',
        'cv' => '',
        'telephone' => '3340245986',
    ],
    [
        'user_id' => '6',
        'name' => 'Martina',
        'surname' => 'Seravelli',
        'address' => 'Viale Nazario Sauro, 5',
        'services' => 'Visita neurologica, EEG, EMG, Potenziali Evocati',
        'photo' => 'avatar/2.png',
        'cv' => '',
        'telephone' => '33012547842',
    ],
    [
        'user_id' => '7',
        'name' => 'Mariarosa',
        'surname' => 'Romeo',
        'address' => 'Via Ugo Bassi, 22',
        'services' => 'Visita dermatologica, Test allergologici',
        'photo' => 'avatar/4.png',
        'cv' => '',
        'telephone' => '3334869977',
    ],
    [
        'user_id' => '8',
        'name' => 'Sergio',
        'surname' => 'Piombino',
        'address' => 'Via Giulio Cesare Procaccini, 4',
        'services' => 'Impedenzometria, Potenziali evocati, Test vestibolare',
        'photo' => 'avatar/8.png',
        'cv' => '',
        'telephone' => '3398456211',
    ],
    [
        'user_id' => '9',
        'name' => 'Carla',
        'surname' => 'Rando',
        'address' => 'Via Monte Amiata, 9',
        'services' => 'Colloquio psichiatrico, Elettroencefalogramma, Visita neurologica',
        'photo' => 'avatar/5.png',
        'cv' => '',
        'telephone' => '3154206974',
    ],
    [
        'user_id' => '10',
        'name' => 'Chiara',
        'surname' => 'Pirozzi',
        'address' => 'Via Alfonso Lamarmora, 8',
        'services' => "Visita ginecologica, Test HPV, Ecografia, Possibilità di praticare l'aborto",
        'photo' => 'avatar/7.png',
        'cv' => '',
        'telephone' => '3342018799',
    ],
    [
        'user_id' => '11',
        'name' => 'Giorgia',
        'surname' => 'Marconi',
        'address' => 'Via Fata Morgana, 22',
        'services' => "Ecografia toracica, ecografia capo e collo",
        'photo' => 'avatar/1.png',
        'cv' => '',
        'telephone' => '3351278496',
    ],
    [
        'user_id' => '12',
        'name' => 'Simone',
        'surname' => 'Rossi',
        'address' => 'Via Napoleone, 17',
        'services' => "Analisi campo visivo, Fluorangiografia",
        'photo' => 'avatar/3.png',
        'cv' => '',
        'telephone' => '3334587799',
    ],
    [
        'user_id' => '13',
        'name' => 'Giorgio',
        'surname' => 'Grasso',
        'address' => 'Via dei Mille, 44',
        'services' => "Impedenzometria, Potenziali evocati acustici, Test vestibolare",
        'photo' => 'avatar/11.png',
        'cv' => '',
        'telephone' => '3698541267',
    ],
    [
        'user_id' => '14',
        'name' => 'Sara',
        'surname' => 'Panebianco',
        'address' => 'Viale della Libertà, 18',
        'services' => "Logopedia",
        'photo' => 'avatar/2.png',
        'cv' => '',
        'telephone' => '3312444569',
    ],
    [
        'user_id' => '15',
        'name' => 'Giorgio',
        'surname' => 'Valli',
        'address' => 'Via Risorgimento, 1',
        'services' => "Elettroencefalogramma, Elettromiografia, Visita Neurologica",
        'photo' => 'avatar/10.png',
        'cv' => '',
        'telephone' => '3342115587',
    ],
    [
        'user_id' => '16',
        'name' => 'Marco',
        'surname' => 'Lori',
        'address' => 'Via Melchiorre, 22',
        'services' => "Test allergologici",
        'photo' => 'avatar/9.png',
        'cv' => '',
        'telephone' => '3314587722',
    ],
    [
        'user_id' => '17',
        'name' => 'Mariacarla',
        'surname' => 'Serafini',
        'address' => 'Via Marco Polo, 15',
        'services' => "TC Collo, TC Rene, TC Massiccio Facciale",
        'photo' => 'avatar/4.png',
        'cv' => '',
        'telephone' => '3325584624',
    ],
    [
        'user_id' => '18',
        'name' => 'Franco',
        'surname' => 'Scoglio',
        'address' => 'Viale della Panoramica, 11',
        'services' => "Urografia endovenosa, Radiografia ossea e delle articolazioni",
        'photo' => 'avatar/8.png',
        'cv' => '',
        'telephone' => '332669485',
    ],
    [
        'user_id' => '19',
        'name' => 'Giuseppe',
        'surname' => 'Calogero',
        'address' => 'Via Noviziato, 2',
        'services' => "RM Torace e miocardio, RM Muscoloscheletrica",
        'photo' => 'avatar/6.png',
        'cv' => '',
        'telephone' => '3369995482',
    ],
    [
        'user_id' => '20',
        'name' => 'Antonio',
        'surname' => 'Mirulla',
        'address' => 'Via delle Lucciole, 11',
        'services' => "Colloquio psichiatrico, Elettroencefalogramma, Visita neurologica",
        'photo' => 'avatar/3.png',
        'cv' => '',
        'telephone' => '332745698',
    ],
    [
        'user_id' => '21',
        'name' => 'Oriana',
        'surname' => 'Franchi',
        'address' => 'Viale Gazzi, 5',
        'services' => "Impedenzometria, Potenziali evocati acustici, Test vestibolare",
        'photo' => 'avatar/5.png',
        'cv' => '',
        'telephone' => '3312599864',
    ],
    [
        'user_id' => '22',
        'name' => 'Alessandro',
        'surname' => 'Giorgi',
        'address' => 'Via del Fante, 8',
        'services' => "Coronarografia, Trattamento cataratta, Visita oculistica",
        'photo' => 'avatar/11.png',
        'cv' => '',
        'telephone' => '3312254896',
    ],
    [
        'user_id' => '23',
        'name' => 'Elena',
        'surname' => 'Denici',
        'address' => 'Via Alfonso Lamarmora, 8',
        'services' => "Analisi campo visivo, Fluorangiografia",
        'photo' => 'avatar/7.png',
        'cv' => '',
        'telephone' => '3324415578',
    ],
    [
        'user_id' => '24',
        'name' => 'Rossana',
        'surname' => 'Saruzzi',
        'address' => 'Via delle vespe, 12',
        'services' => "Ecocolordoppler dei vasi periferici, Ecocolordoppler dei tronchi sovra aortici, Elettrocardiogramma holter",
        'photo' => 'avatar/1.png',
        'cv' => '',
        'telephone' => '3387456695',
    ],
    [
        'user_id' => '25',
        'name' => 'Marco',
        'surname' => 'Palmara',
        'address' => 'Contrada Cicerina, 6',
        'services' => "Visita ginecologica, Test HPV, Ecografia, Possibilità di praticare l'aborto",
        'photo' => 'avatar/10.png',
        'cv' => '',
        'telephone' => '3345988766',
    ],
    [
        'user_id' => '26',
        'name' => 'Carlotta',
        'surname' => 'Marmora',
        'address' => 'Via Colli S. Rizzo, 7',
        'services' => "Visita dermatologica, Test allergologici",
        'photo' => 'avatar/2.png',
        'cv' => '',
        'telephone' => '3342018799',
    ],
    [
        'user_id' => '27',
        'name' => 'Biagio',
        'surname' => 'Leori',
        'address' => 'Viale S. Martino, 19',
        'services' => "Riabilitazione motoria, Riabilitazione respiratoria, Logopedia",
        'photo' => 'avatar/9.png',
        'cv' => '',
        'telephone' => '3339985472',
    ],
    [
        'user_id' => '28',
        'name' => 'Paolo',
        'surname' => 'Meneghini',
        'address' => 'Via Ugo Bassi, 33',
        'services' => "Ecocolordoppler dei vasi periferici, Ecocolordoppler dei tronchi sovra aortici, Elettrocardiogramma holter",
        'photo' => 'avatar/8.png',
        'cv' => '',
        'telephone' => '3226599861',
    ],
    [
        'user_id' => '29',
        'name' => 'Francesca',
        'surname' => 'Bartolini',
        'address' => 'Via Boner, 11',
        'services' => "RM Torace e miocardio, RM Muscoloscheletrica, RM colonna vertebrale",
        'photo' => 'avatar/4.png',
        'cv' => '',
        'telephone' => '3336985584',
    ],
    [
        'user_id' => '30',
        'name' => 'Giulia',
        'surname' => 'Rovere',
        'address' => 'Via Tommaso Cannizzaro, 6',
        'services' => "Colloquio psichiatrico, Elettroencefalogramma, Visita neurologica",
        'photo' => 'avatar/5.png',
        'cv' => 'avatar/3.png',
        'telephone' => '3696551240',
    ],
    [
        'user_id' => '31',
        'name' => 'Bernardo',
        'surname' => 'Dalia',
        'address' => 'Via Missori, 8',
        'services' => "Radiografia ossea e delle articolazioni, Radiografia completa del tubo digerente, Radiografia completa del tubo digerente",
        'photo' => 'avatar/11.png',
        'cv' => '',
        'telephone' => '3669854110',
    ],
    [
        'user_id' => '32',
        'name' => 'Emanuele',
        'surname' => 'Allegra',
        'address' => 'Viale delle donnole, 11',
        'services' => "TC Collo, TC Rene, TC Massiccio Facciale",
        'photo' => 'avatar/10.png',
        'cv' => '',
        'telephone' => '3021220445',
    ],
    [
        'user_id' => '33',
        'name' => 'Simona',
        'surname' => 'De Meo',
        'address' => 'Via Minici, 15',
        'services' => "Visita ginecologica, Test HPV, Ecografia, Possibilità di praticare l'aborto",
        'photo' => 'avatar/7.png',
        'cv' => 'avatar/9.png',
        'telephone' => '33100526999',
    ],
    [
        'user_id' => '34',
        'name' => 'Carla',
        'surname' => 'Minici',
        'address' => 'Via dei Portici, 22',
        'services' => "Scienze dell'Alimentazione, Medicina estetica, Terapia del dolore",
        'photo' => 'avatar/1.png',
        'cv' => '',
        'telephone' => '3330015774',
    ],
    [
        'user_id' => '35',
        'name' => 'Alessandra',
        'surname' => 'Dantoni',
        'address' => 'Via Merrini, 1',
        'services' => "Riabilitazione motoria, Riabilitazione respiratoria, Logopedia",
        'photo' => 'avatar/2.png',
        'cv' => '',
        'telephone' => '3306958842',
    ],
    [
        'user_id' => '36',
        'name' => 'Silvia',
        'surname' => 'Formini',
        'address' => 'Piazza del Popolo, 7',
        'services' => "Radiografia ossea e delle articolazioni, Radiografia completa del tubo digerente, Radiografia completa del tubo digerente",
        'photo' => 'avatar/4.png',
        'cv' => '',
        'telephone' => '3339953012',
    ],
    [
        'user_id' => '37',
        'name' => 'Francesco',
        'surname' => 'Bottari',
        'address' => 'Via Santa Marta, 44',
        'services' => "Visita neurologica, EEG, EMG, Potenziali Evocati",
        'photo' => 'avatar/8.png',
        'cv' => '',
        'telephone' => '3669980120',
    ],
    [
        'user_id' => '38',
        'name' => 'Marco',
        'surname' => 'Vieri',
        'address' => 'Piazza Plebiscito, 4',
        'services' => "Visita ginecologica, Test HPV, Ecografia, Possibilità di praticare l'aborto",
        'photo' => 'avatar/6.png',
        'cv' => '',
        'telephone' => '3310024789',
    ],
    [
        'user_id' => '39',
        'name' => 'Emily',
        'surname' => 'Novik',
        'address' => 'Via Marconi, 15',
        'services' => "Scienze dell'Alimentazione, Medicina estetica, Terapia del dolore",
        'photo' => 'avatar/5.png',
        'cv' => '',
        'telephone' => '3338756921',
    ],
    [
        'user_id' => '40',
        'name' => 'Orazio',
        'surname' => 'Sordi',
        'address' => 'Via Melchiorre, 9',
        'services' => "Coronarografia, Trattamento cataratta, Visita oculistica",
        'photo' => 'avatar/3.png',
        'cv' => '',
        'telephone' => '3312006745',
    ],
    [
        'user_id' => '41',
        'name' => 'Milo',
        'surname' => 'Marziali',
        'address' => 'Via Pompeo, 7',
        'services' => "Scienze dell'Alimentazione, Medicina estetica, Terapia del dolore",
        'photo' => 'avatar/11.png',
        'cv' => '',
        'telephone' => '3202486129',
    ],
    [
        'user_id' => '42',
        'name' => 'Cristian',
        'surname' => 'Pellegrini',
        'address' => 'Via Lodovico, 15',
        'services' => 'Ecocolordoppler dei vasi periferici, Ecocolordoppler dei tronchi sovra aortici, Elettrocardiogramma holter',
        'photo' => 'avatar/10.png',
        'cv' => '',
        'telephone' => '3985421605',
    ],
    [
        'user_id' => '43',
        'name' => 'Marco',
        'surname' => 'Zampieri',
        'address' => 'Via degli Oleandri, 11',
        'services' => 'Coronarografia, Trattamento cataratta, Visita oculistica',
        'photo' => 'avatar/9.png',
        'cv' => '',
        'telephone' => '3201542097',
    ],
    [
        'user_id' => '44',
        'name' => 'Vilma Maria',
        'surname' => 'Crivellaro',
        'address' => 'Via Baggio, 20',
        'services' => 'Radiografia ossea e delle articolazioni, Radiografia completa del tubo digerente, Radiografia completa del tubo digerente',
        'photo' => 'avatar/1.png',
        'cv' => '',
        'telephone' => '3501248961',
    ],
    [
        'user_id' => '45',
        'name' => 'Giorgio',
        'surname' => 'Francuzzi',
        'address' => 'Via Mar Nero, 30',
        'services' => 'Riabilitazione motoria, Riabilitazione respiratoria, Logopedia',
        'photo' => 'avatar/6.png',
        'cv' => '',
        'telephone' => '3340245986',
    ],
    [
        'user_id' => '46',
        'name' => 'Martina',
        'surname' => 'Seravelli',
        'address' => 'Viale Nazario Sauro, 5',
        'services' => 'Visita neurologica, EEG, EMG, Potenziali Evocati',
        'photo' => 'avatar/2.png',
        'cv' => '',
        'telephone' => '33012547842',
    ],
    [
        'user_id' => '47',
        'name' => 'Mariarosa',
        'surname' => 'Romeo',
        'address' => 'Via Ugo Bassi, 22',
        'services' => 'Visita dermatologica, Test allergologici',
        'photo' => 'avatar/4.png',
        'cv' => '',
        'telephone' => '3334869977',
    ],
    [
        'user_id' => '48',
        'name' => 'Sergio',
        'surname' => 'Piombino',
        'address' => 'Via Giulio Cesare Procaccini, 4',
        'services' => 'Impedenzometria, Potenziali evocati, Test vestibolare',
        'photo' => 'avatar/8.png',
        'cv' => '',
        'telephone' => '3398456211',
    ],
    [
        'user_id' => '49',
        'name' => 'Carla',
        'surname' => 'Rando',
        'address' => 'Via Monte Amiata, 9',
        'services' => 'Colloquio psichiatrico, Elettroencefalogramma, Visita neurologica',
        'photo' => 'avatar/5.png',
        'cv' => '',
        'telephone' => '3154206974',
    ],
    [
        'user_id' => '50',
        'name' => 'Chiara',
        'surname' => 'Pirozzi',
        'address' => 'Via Alfonso Lamarmora, 8',
        'services' => "Visita ginecologica, Test HPV, Ecografia, Possibilità di praticare l'aborto",
        'photo' => 'avatar/7.png',
        'cv' => '',
        'telephone' => '3342018799',
    ],
    [
        'user_id' => '51',
        'name' => 'Giorgia',
        'surname' => 'Marconi',
        'address' => 'Via Fata Morgana, 22',
        'services' => "Ecografia toracica, ecografia capo e collo",
        'photo' => 'avatar/1.png',
        'cv' => '',
        'telephone' => '3351278496',
    ],
    [
        'user_id' => '52',
        'name' => 'Simone',
        'surname' => 'Rossi',
        'address' => 'Via Napoleone, 17',
        'services' => "Analisi campo visivo, Fluorangiografia",
        'photo' => 'avatar/3.png',
        'cv' => '',
        'telephone' => '3334587799',
    ],
    [
        'user_id' => '53',
        'name' => 'Giorgio',
        'surname' => 'Grasso',
        'address' => 'Via dei Mille, 44',
        'services' => "Impedenzometria, Potenziali evocati acustici, Test vestibolare",
        'photo' => 'avatar/11.png',
        'cv' => '',
        'telephone' => '3698541267',
    ],
    [
        'user_id' => '54',
        'name' => 'Sara',
        'surname' => 'Panebianco',
        'address' => 'Viale della Libertà, 18',
        'services' => "Logopedia",
        'photo' => 'avatar/2.png',
        'cv' => '',
        'telephone' => '3312444569',
    ],
    [
        'user_id' => '55',
        'name' => 'Giorgio',
        'surname' => 'Valli',
        'address' => 'Via Risorgimento, 1',
        'services' => "Elettroencefalogramma, Elettromiografia, Visita Neurologica",
        'photo' => 'avatar/10.png',
        'cv' => '',
        'telephone' => '3342115587',
    ],
    [
        'user_id' => '56',
        'name' => 'Marco',
        'surname' => 'Lori',
        'address' => 'Via Melchiorre, 22',
        'services' => "Test allergologici",
        'photo' => 'avatar/9.png',
        'cv' => '',
        'telephone' => '3314587722',
    ],
    [
        'user_id' => '57',
        'name' => 'Mariacarla',
        'surname' => 'Serafini',
        'address' => 'Via Marco Polo, 15',
        'services' => "TC Collo, TC Rene, TC Massiccio Facciale",
        'photo' => 'avatar/4.png',
        'cv' => '',
        'telephone' => '3325584624',
    ],
    [
        'user_id' => '58',
        'name' => 'Franco',
        'surname' => 'Scoglio',
        'address' => 'Viale della Panoramica, 11',
        'services' => "Urografia endovenosa, Radiografia ossea e delle articolazioni",
        'photo' => 'avatar/8.png',
        'cv' => '',
        'telephone' => '332669485',
    ],
    [
        'user_id' => '59',
        'name' => 'Giuseppe',
        'surname' => 'Calogero',
        'address' => 'Via Noviziato, 2',
        'services' => "RM Torace e miocardio, RM Muscoloscheletrica",
        'photo' => 'avatar/6.png',
        'cv' => '',
        'telephone' => '3369995482',
    ],
    [
        'user_id' => '60',
        'name' => 'Antonio',
        'surname' => 'Mirulla',
        'address' => 'Via delle Lucciole, 11',
        'services' => "Colloquio psichiatrico, Elettroencefalogramma, Visita neurologica",
        'photo' => 'avatar/3.png',
        'cv' => '',
        'telephone' => '332745698',
    ],
    [
        'user_id' => '61',
        'name' => 'Oriana',
        'surname' => 'Franchi',
        'address' => 'Viale Gazzi, 5',
        'services' => "Impedenzometria, Potenziali evocati acustici, Test vestibolare",
        'photo' => 'avatar/5.png',
        'cv' => '',
        'telephone' => '3312599864',
    ],
    [
        'user_id' => '62',
        'name' => 'Alessandro',
        'surname' => 'Giorgi',
        'address' => 'Via del Fante, 8',
        'services' => "Coronarografia, Trattamento cataratta, Visita oculistica",
        'photo' => 'avatar/11.png',
        'cv' => '',
        'telephone' => '3312254896',
    ],
    [
        'user_id' => '63',
        'name' => 'Elena',
        'surname' => 'Denici',
        'address' => 'Via Alfonso Lamarmora, 8',
        'services' => "Analisi campo visivo, Fluorangiografia",
        'photo' => 'avatar/7.png',
        'cv' => '',
        'telephone' => '3324415578',
    ],
    [
        'user_id' => '64',
        'name' => 'Rossana',
        'surname' => 'Saruzzi',
        'address' => 'Via delle vespe, 12',
        'services' => "Ecocolordoppler dei vasi periferici, Ecocolordoppler dei tronchi sovra aortici, Elettrocardiogramma holter",
        'photo' => 'avatar/1.png',
        'cv' => '',
        'telephone' => '3387456695',
    ],
    [
        'user_id' => '65',
        'name' => 'Marco',
        'surname' => 'Palmara',
        'address' => 'Contrada Cicerina, 6',
        'services' => "Visita ginecologica, Test HPV, Ecografia, Possibilità di praticare l'aborto",
        'photo' => 'avatar/10.png',
        'cv' => '',
        'telephone' => '3345988766',
    ],
    [
        'user_id' => '66',
        'name' => 'Carlotta',
        'surname' => 'Marmora',
        'address' => 'Via Colli S. Rizzo, 7',
        'services' => "Visita dermatologica, Test allergologici",
        'photo' => 'avatar/2.png',
        'cv' => '',
        'telephone' => '3342018799',
    ],
    [
        'user_id' => '67',
        'name' => 'Biagio',
        'surname' => 'Leori',
        'address' => 'Viale S. Martino, 19',
        'services' => "Riabilitazione motoria, Riabilitazione respiratoria, Logopedia",
        'photo' => 'avatar/9.png',
        'cv' => '',
        'telephone' => '3339985472',
    ],
    [
        'user_id' => '68',
        'name' => 'Paolo',
        'surname' => 'Meneghini',
        'address' => 'Via Ugo Bassi, 33',
        'services' => "Ecocolordoppler dei vasi periferici, Ecocolordoppler dei tronchi sovra aortici, Elettrocardiogramma holter",
        'photo' => 'avatar/8.png',
        'cv' => '',
        'telephone' => '3226599861',
    ],
    [
        'user_id' => '69',
        'name' => 'Francesca',
        'surname' => 'Bartolini',
        'address' => 'Via Boner, 11',
        'services' => "RM Torace e miocardio, RM Muscoloscheletrica, RM colonna vertebrale",
        'photo' => 'avatar/4.png',
        'cv' => '',
        'telephone' => '3336985584',
    ],
    [
        'user_id' => '70',
        'name' => 'Giulia',
        'surname' => 'Rovere',
        'address' => 'Via Tommaso Cannizzaro, 6',
        'services' => "Colloquio psichiatrico, Elettroencefalogramma, Visita neurologica",
        'photo' => 'avatar/5.png',
        'cv' => 'avatar/3.png',
        'telephone' => '3696551240',
    ],
    [
        'user_id' => '71',
        'name' => 'Bernardo',
        'surname' => 'Dalia',
        'address' => 'Via Missori, 8',
        'services' => "Radiografia ossea e delle articolazioni, Radiografia completa del tubo digerente, Radiografia completa del tubo digerente",
        'photo' => 'avatar/11.png',
        'cv' => '',
        'telephone' => '3669854110',
    ],
    [
        'user_id' => '72',
        'name' => 'Emanuele',
        'surname' => 'Allegra',
        'address' => 'Viale delle donnole, 11',
        'services' => "TC Collo, TC Rene, TC Massiccio Facciale",
        'photo' => 'avatar/10.png',
        'cv' => '',
        'telephone' => '3021220445',
    ],
    [
        'user_id' => '73',
        'name' => 'Simona',
        'surname' => 'De Meo',
        'address' => 'Via Minici, 15',
        'services' => "Visita ginecologica, Test HPV, Ecografia, Possibilità di praticare l'aborto",
        'photo' => 'avatar/7.png',
        'cv' => 'avatar/9.png',
        'telephone' => '33100526999',
    ],
    [
        'user_id' => '74',
        'name' => 'Carla',
        'surname' => 'Minici',
        'address' => 'Via dei Portici, 22',
        'services' => "Scienze dell'Alimentazione, Medicina estetica, Terapia del dolore",
        'photo' => 'avatar/1.png',
        'cv' => '',
        'telephone' => '3330015774',
    ],
    [
        'user_id' => '75',
        'name' => 'Alessandra',
        'surname' => 'Dantoni',
        'address' => 'Via Merrini, 1',
        'services' => "Riabilitazione motoria, Riabilitazione respiratoria, Logopedia",
        'photo' => 'avatar/2.png',
        'cv' => '',
        'telephone' => '3306958842',
    ],
    [
        'user_id' => '76',
        'name' => 'Silvia',
        'surname' => 'Formini',
        'address' => 'Piazza del Popolo, 7',
        'services' => "Radiografia ossea e delle articolazioni, Radiografia completa del tubo digerente, Radiografia completa del tubo digerente",
        'photo' => 'avatar/4.png',
        'cv' => '',
        'telephone' => '3339953012',
    ],
    [
        'user_id' => '77',
        'name' => 'Francesco',
        'surname' => 'Bottari',
        'address' => 'Via Santa Marta, 44',
        'services' => "Visita neurologica, EEG, EMG, Potenziali Evocati",
        'photo' => 'avatar/8.png',
        'cv' => '',
        'telephone' => '3669980120',
    ],
    [
        'user_id' => '78',
        'name' => 'Marco',
        'surname' => 'Vieri',
        'address' => 'Piazza Plebiscito, 4',
        'services' => "Visita ginecologica, Test HPV, Ecografia, Possibilità di praticare l'aborto",
        'photo' => 'avatar/6.png',
        'cv' => '',
        'telephone' => '3310024789',
    ],
    [
        'user_id' => '79',
        'name' => 'Emily',
        'surname' => 'Novik',
        'address' => 'Via Marconi, 15',
        'services' => "Scienze dell'Alimentazione, Medicina estetica, Terapia del dolore",
        'photo' => 'avatar/5.png',
        'cv' => '',
        'telephone' => '3338756921',
    ],
    [
        'user_id' => '80',
        'name' => 'Orazio',
        'surname' => 'Sordi',
        'address' => 'Via Melchiorre, 9',
        'services' => "Coronarografia, Trattamento cataratta, Visita oculistica",
        'photo' => 'avatar/3.png',
        'cv' => '',
        'telephone' => '3312006745',
    ],
    [
        'user_id' => '81',
        'name' => 'Milo',
        'surname' => 'Marziali',
        'address' => 'Via Pompeo, 7',
        'services' => "Scienze dell'Alimentazione, Medicina estetica, Terapia del dolore",
        'photo' => 'avatar/11.png',
        'cv' => '',
        'telephone' => '3202486129',
    ],
    [
        'user_id' => '82',
        'name' => 'Cristian',
        'surname' => 'Pellegrini',
        'address' => 'Via Lodovico, 15',
        'services' => 'Ecocolordoppler dei vasi periferici, Ecocolordoppler dei tronchi sovra aortici, Elettrocardiogramma holter',
        'photo' => 'avatar/10.png',
        'cv' => '',
        'telephone' => '3985421605',
    ],
    [
        'user_id' => '83',
        'name' => 'Marco',
        'surname' => 'Zampieri',
        'address' => 'Via degli Oleandri, 11',
        'services' => 'Coronarografia, Trattamento cataratta, Visita oculistica',
        'photo' => 'avatar/9.png',
        'cv' => '',
        'telephone' => '3201542097',
    ],
    [
        'user_id' => '84',
        'name' => 'Vilma Maria',
        'surname' => 'Crivellaro',
        'address' => 'Via Baggio, 20',
        'services' => 'Radiografia ossea e delle articolazioni, Radiografia completa del tubo digerente, Radiografia completa del tubo digerente',
        'photo' => 'avatar/1.png',
        'cv' => '',
        'telephone' => '3501248961',
    ],
    [
        'user_id' => '85',
        'name' => 'Giorgio',
        'surname' => 'Francuzzi',
        'address' => 'Via Mar Nero, 30',
        'services' => 'Riabilitazione motoria, Riabilitazione respiratoria, Logopedia',
        'photo' => 'avatar/6.png',
        'cv' => '',
        'telephone' => '3340245986',
    ],
    [
        'user_id' => '86',
        'name' => 'Martina',
        'surname' => 'Seravelli',
        'address' => 'Viale Nazario Sauro, 5',
        'services' => 'Visita neurologica, EEG, EMG, Potenziali Evocati',
        'photo' => 'avatar/2.png',
        'cv' => '',
        'telephone' => '33012547842',
    ],
    [
        'user_id' => '87',
        'name' => 'Mariarosa',
        'surname' => 'Romeo',
        'address' => 'Via Ugo Bassi, 22',
        'services' => 'Visita dermatologica, Test allergologici',
        'photo' => 'avatar/4.png',
        'cv' => '',
        'telephone' => '3334869977',
    ],
    [
        'user_id' => '88',
        'name' => 'Sergio',
        'surname' => 'Piombino',
        'address' => 'Via Giulio Cesare Procaccini, 4',
        'services' => 'Impedenzometria, Potenziali evocati, Test vestibolare',
        'photo' => 'avatar/8.png',
        'cv' => '',
        'telephone' => '3398456211',
    ],
    [
        'user_id' => '89',
        'name' => 'Carla',
        'surname' => 'Rando',
        'address' => 'Via Monte Amiata, 9',
        'services' => 'Colloquio psichiatrico, Elettroencefalogramma, Visita neurologica',
        'photo' => 'avatar/5.png',
        'cv' => '',
        'telephone' => '3154206974',
    ],
    [
        'user_id' => '90',
        'name' => 'Chiara',
        'surname' => 'Pirozzi',
        'address' => 'Via Alfonso Lamarmora, 8',
        'services' => "Visita ginecologica, Test HPV, Ecografia, Possibilità di praticare l'aborto",
        'photo' => 'avatar/7.png',
        'cv' => '',
        'telephone' => '3342018799',
    ],
    [
        'user_id' => '91',
        'name' => 'Giorgia',
        'surname' => 'Marconi',
        'address' => 'Via Fata Morgana, 22',
        'services' => "Ecografia toracica, ecografia capo e collo",
        'photo' => 'avatar/1.png',
        'cv' => '',
        'telephone' => '3351278496',
    ],
    [
        'user_id' => '92',
        'name' => 'Simone',
        'surname' => 'Rossi',
        'address' => 'Via Napoleone, 17',
        'services' => "Analisi campo visivo, Fluorangiografia",
        'photo' => 'avatar/3.png',
        'cv' => '',
        'telephone' => '3334587799',
    ],
    [
        'user_id' => '93',
        'name' => 'Giorgio',
        'surname' => 'Grasso',
        'address' => 'Via dei Mille, 44',
        'services' => "Impedenzometria, Potenziali evocati acustici, Test vestibolare",
        'photo' => 'avatar/11.png',
        'cv' => '',
        'telephone' => '3698541267',
    ],
    [
        'user_id' => '94',
        'name' => 'Sara',
        'surname' => 'Panebianco',
        'address' => 'Viale della Libertà, 18',
        'services' => "Logopedia",
        'photo' => 'avatar/2.png',
        'cv' => '',
        'telephone' => '3312444569',
    ],
    [
        'user_id' => '95',
        'name' => 'Giorgio',
        'surname' => 'Valli',
        'address' => 'Via Risorgimento, 1',
        'services' => "Elettroencefalogramma, Elettromiografia, Visita Neurologica",
        'photo' => 'avatar/10.png',
        'cv' => '',
        'telephone' => '3342115587',
    ],
    [
        'user_id' => '96',
        'name' => 'Marco',
        'surname' => 'Lori',
        'address' => 'Via Melchiorre, 22',
        'services' => "Test allergologici",
        'photo' => 'avatar/9.png',
        'cv' => '',
        'telephone' => '3314587722',
    ],
    [
        'user_id' => '97',
        'name' => 'Mariacarla',
        'surname' => 'Serafini',
        'address' => 'Via Marco Polo, 15',
        'services' => "TC Collo, TC Rene, TC Massiccio Facciale",
        'photo' => 'avatar/4.png',
        'cv' => '',
        'telephone' => '3325584624',
    ],
    [
        'user_id' => '98',
        'name' => 'Franco',
        'surname' => 'Scoglio',
        'address' => 'Viale della Panoramica, 11',
        'services' => "Urografia endovenosa, Radiografia ossea e delle articolazioni",
        'photo' => 'avatar/8.png',
        'cv' => '',
        'telephone' => '332669485',
    ],
    [
        'user_id' => '99',
        'name' => 'Giuseppe',
        'surname' => 'Calogero',
        'address' => 'Via Noviziato, 2',
        'services' => "RM Torace e miocardio, RM Muscoloscheletrica",
        'photo' => 'avatar/6.png',
        'cv' => '',
        'telephone' => '3369995482',
    ],
    [
        'user_id' => '100',
        'name' => 'Antonio',
        'surname' => 'Mirulla',
        'address' => 'Via delle Lucciole, 11',
        'services' => "Colloquio psichiatrico, Elettroencefalogramma, Visita neurologica",
        'photo' => 'avatar/3.png',
        'cv' => '',
        'telephone' => '332745698',
    ],
]

?>